# Generated by Django 5.2.15 on 2026-06-17 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombres", models.CharField(max_length=100)),
                ("apellidos", models.CharField(max_length=100)),
                ("identificacion", models.CharField(max_length=20, unique=True)),
                ("telefono", models.CharField(blank=True, max_length=20)),
                ("celular", models.CharField(blank=True, max_length=20)),
                ("correo", models.EmailField(blank=True, max_length=254)),
                ("direccion", models.TextField(blank=True)),
                (
                    "estado_civil",
                    models.CharField(
                        choices=[
                            ("soltero", "Soltero/a"),
                            ("casado", "Casado/a"),
                            ("divorciado", "Divorciado/a"),
                            ("viudo", "Viudo/a"),
                        ],
                        default="soltero",
                        max_length=20,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("activo", "Activo"), ("inactivo", "Inactivo")],
                        default="activo",
                        max_length=10,
                    ),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "ordering": ["apellidos", "nombres"],
            },
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("Bebidas Calientes", "Bebidas Calientes"),
                            ("Bebidas Frías", "Bebidas Frías"),
                            ("Snacks", "Snacks"),
                        ],
                        max_length=50,
                    ),
                ),
                ("precio", models.DecimalField(decimal_places=2, max_digits=8)),
                ("disponible", models.BooleanField(default=True)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
                "ordering": ["categoria", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mesa", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("en preparación", "En preparación"),
                            ("entregado", "Entregado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pedidos",
                        to="api.cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pedido",
                "verbose_name_plural": "Pedidos",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="DetallePedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField(default=1)),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="api.pedido",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="detalles",
                        to="api.producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Pedido",
                "verbose_name_plural": "Detalles de Pedido",
            },
        ),
    ]
